CREATE TABLE IF NOT EXISTS "FiscalYears" 
(
	"FiscalYearsId"	INTEGER NOT NULL UNIQUE,
	"BFY"	TEXT(80) DEFAULT 'NS',
	"EFY"	TEXT(80) DEFAULT 'NS',
	"StartDate"	TEXT(80) DEFAULT 'NS',
	"ColumbusDay"	TEXT(80) DEFAULT 'NS',
	"VeteransDay"	TEXT(80) DEFAULT 'NS',
	"ThanksgivingDay"	TEXT(80) DEFAULT 'NS',
	"ChristmasDay"	TEXT(80) DEFAULT 'NS',
	"NewYearsDay"	TEXT(80) DEFAULT 'NS',
	"MartinLutherKingsDay"	TEXT(80) DEFAULT 'NS',
	"WashingtonsDay"	TEXT(80) DEFAULT 'NS',
	"MemorialDay"	TEXT(80) DEFAULT 'NS',
	"JuneteenthDay"	TEXT(80) DEFAULT 'NS',
	"IndependenceDay"	TEXT(80) DEFAULT 'NS',
	"LaborDay"	TEXT(80) DEFAULT 'NS',
	"ExpiringYear"	TEXT(80) DEFAULT 'NS',
	"ExpirationDate"	TEXT(80) DEFAULT 'NS',
	"WorkDays"	INTEGER,
	"WeekDays"	INTEGER,
	"WeekEnds"	INTEGER,
	"EndDate"	TEXT(80) DEFAULT 'NS',
	"Availability"	TEXT(80) DEFAULT 'NS',
	PRIMARY KEY("FiscalYearsId" AUTOINCREMENT)
);
