CREATE TABLE IF NOT EXISTS "BudgetaryResourceExecution" 
(
	"BudgetaryResourceExecutionId"	INTEGER,
	"ReportYear"	TEXT(80) DEFAULT 'NS',
	"BeginningPeriodOfAvailability"	TEXT(80) DEFAULT 'NS',
	"EndingPeriodOfAvailability"	TEXT(80) DEFAULT 'NS',
	"Agency"	TEXT(80) DEFAULT 'NS',
	"Bureau"	TEXT(80) DEFAULT 'NS',
	"BudgetAgencyCode"	TEXT(80) DEFAULT 'NS',
	"BudgetBureauCode"	TEXT(80) DEFAULT 'NS',
	"BudgetAccountCode"	TEXT(80) DEFAULT 'NS',
	"BudgetAccountName"	TEXT(80) DEFAULT 'NS',
	"TreasuryAgencyCode"	TEXT(80) DEFAULT 'NS',
	"AllocationAccount"	TEXT(80) DEFAULT 'NS',
	"TreasuryAccountCode"	TEXT(80) DEFAULT 'NS',
	"TreasuryAccountName"	TEXT(80) DEFAULT 'NS',
	"TreasuryFundSymbol"	TEXT(80) DEFAULT 'NS',
	"LineNumber"	TEXT(80) DEFAULT 'NS',
	"LineDescription"	TEXT(80) DEFAULT 'NS',
	"SectionName"	TEXT(80) DEFAULT 'NS',
	"SectionNumber"	TEXT(80) DEFAULT 'NS',
	"LineType"	TEXT(80) DEFAULT 'NS',
	"Updated"	TEXT(80) DEFAULT 'NS',
	"November"	REAL DEFAULT 0.00,
	"December"	REAL DEFAULT 0.00,
	"January"	REAL DEFAULT 0.00,
	"Feburary"	REAL DEFAULT 0.00,
	"March"	REAL DEFAULT 0.00,
	"April"	REAL DEFAULT 0.00,
	"May"	REAL DEFAULT 0.00,
	"June"	REAL DEFAULT 0.00,
	"July"	REAL DEFAULT 0.00,
	"August"	REAL DEFAULT 0.00,
	"September"	REAL DEFAULT 0.00,
	"October"	REAL DEFAULT 0.00
);