CREATE TABLE IF NOT EXISTS "ChatLog" 
(
	"ID"	INTEGER NOT NULL UNIQUE,
	"Time"	TEXT(80) DEFAULT 'NS',
	"Role"	TEXT(80) DEFAULT 'NS',
	"Content"	TEXT(80) DEFAULT 'NS',
	CONSTRAINT "ChatLogPrimaryKey" PRIMARY KEY("ID" AUTOINCREMENT)
);